version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POPOSTGRES_USER: postgres
      POSTGRES_DB: nest
    ports:
      - 5432:5432
    volumes:
      - ./PostgreVolume:/var/lib/postgresql/data
    networks:
      - nest

networks:
  nest:


